config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"


  resources :lessons, only: [:index, :new, :create, :show, :destroy] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]

  # xp user update route à déterminer (ou déjà gérée par devise_for :users)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :lesson, uniqueness: {scope: :user}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  has_many :playlists
  has_many :videos, through: :playlists

  has_one_attached :miniature



  validates :name, presence: true, uniqueness: true
  # validates :duration, lenght: { minimum: 1 }

  # validates :breathing, presence: true
  # validates :posture, presence: true
  # validates :meditation, presence: true

  # validates :level, inclusion: { in: %w[beginner intermediate advanced], message: "%{value} is not a valid level" }
  # validates :boost, inclusion: { in: %w[Neck Chest Backbend Hips Hamstring Twits], message: "%{value} is not a valid boost"}
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :lesson
  belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :favorites, dependent: :destroy
  has_many :lessons, dependent: :destroy

  has_one_attached :avatar

end

app/models/video.rb
class Video < ApplicationRecord
  has_many :playlists

  has_one_attached :miniature
  has_one_attached :content

  validates :name, presence: true, uniqueness: true

  validates :video_category, inclusion: { in: %w[breathing posture meditation], message: "%{value} is not a valid type" }
  validates :boost, inclusion: { in: %w[Neck Chest Backbend Hips Hamstring Twits], message: "%{value} is not a valid boost" }
  validates :level, inclusion: { in: %w[beginner intermediate advanced], message: "%{value} is not a valid level" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:destroy]

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @favorite = Favorite.new(user: current_user, lesson: @lesson)

    if @favorite.save
      flash[:notice] = "Successfully add to your favorite lessons !"
      redirect_to lesson_path(@lesson)
    else
      flash[:alert] = "Already in your favorites lessons."
      redirect_to lesson_path(@lesson)
    end
  end

  def destroy
    @favorite.destroy
    redirect_to profile_path, status: :see_other
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    # @lessons = Lesson.all
    @user = current_user
    start_date = params.fetch(:start_date, Date.today).to_date
    @lessons = Lesson.where(lesson_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def new
    @user = current_user
    @lesson = Lesson.new
  end

  def create
    sleep(6)
    @lesson = Lesson.new(lesson_params)
    @user = current_user
    @lesson.user = @user
    @user.xp += 5
    @user.save
    @lesson.video_url = "https://www.youtube.com/embed/videoseries?si=bfj0BV8G6LJPg0bG&amp;list=PLsQy3ETrPSMG7TJvuvg480UmdDj7MAqDi"
    @lesson.lesson_date = Time.now
    @lesson.start_time = @lesson.lesson_date

    if @lesson.save
      redirect_to lesson_path(@lesson), notice: 'Lesson was successfuly created!'
    else
      render :new
    end
  end

  def show
    @user = current_user
    @lesson = Lesson.find(params[:id])
    @favorite = Favorite.new
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    Favorite.where(lesson: @lesson).destroy_all

    if @lesson.destroy
      flash[:notice] = "Lesson was successfully deleted!"
      redirect_to profile_path
    else
      flash[:alert] = "Error."
      redirect_to profile_path
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:name, :duration, :breathing, :posture, :meditation, :level, :boost)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @user = current_user
  end

  def profile
    @user = current_user
    @favorites = @user.favorites
    @lessons = @user.lessons
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# Favicon  %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css">
    <%= javascript_include_tag "delete_confirmation_dialog" %>
  </head>

  <body>
    <% if current_page?(root_path) %>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/destroy.html.erb
<h1>Lessons#destroy</h1>
<p>Find me in app/views/lessons/destroy.html.erb</p>

app/views/lessons/index.html.erb
<%= month_calendar(events: @lessons) do |date, lessons| %>
  <%= date %>

  <% lessons.each do |lesson| %>
    <div class="lesson" style="background-color: #acceb4;">
      <p><%= link_to lesson.name, lesson_path(lesson) %> 🌻</p>
    </div>
  <% end %>
<% end %>

app/views/lessons/show.html.erb
<div class="container show-container">
  <%# VIDEO YOUTUBE %>
  <div class="d-flex justify-content-center shadow-lg p-3 mb-2 bg-body-tertiary rounded-4">
      <iframe class="flex-item video-iframe" width="1250" height="725" src="<%= @lesson.video_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>

  <div class="d-flex justify-content-between show-information">
    <div class="d-flex justify-content-center">
      <h1 class="lesson-title"><%= @lesson.name  %></h1>
      <p class="lesson-info"><i class="fa-solid fa-wind" style="color: #5c5c5c;"> </i> <%= @lesson.breathing ? "Breathing" : "No Breathing" %></p>
      <p class="lesson-info"><i class="fa-solid fa-layer-group" style="color: #5c5c5c;">  </i> <%= @lesson.level %></p>
      <p class="lesson-info"><i class="fa-solid fa-bolt" style="color: #5c5c5c;">  </i> <%= @lesson.boost %></p>
      <p class="lesson-info"><i class="fa-solid fa-spa" style="color: #5c5c5c;"> </i> <%= @lesson.meditation ? "Meditation" : "No Meditation" %></p>
      <p class="lesson-info"><i class="fa-solid fa-clock" style="color: #5c5c5c;"> </i>  <%= @lesson.duration %></p>
    </div>
    <div class="d-flex justify-content-between ">
      <%= link_to "My History", profile_path, class: "green-btn lesson-button" %>
      <div data-controller="favorites">
        <%= link_to lesson_favorites_path(@lesson), data: {turbo_method: :post, action: "click->favorites#toggleHeart" } do %>
          <% if Favorite.where(user: current_user, lesson: @lesson).present? %>
            <i data-target="favorites.heartIcon" class="fa-solid fa-heart fa-beat fa-2xl show-heart" style="color: #668a6e;"></i>
          <% else %>
            <i data-target="favorites.heartIcon" class="fa-regular fa-heart fa-beat fa-2xl show-heart" style="color: #668a6e;"></i>
          <% end %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage">
  <div class="navbar-expand-sm navbar-light navbar-homepage">
    <%= render "shared/navbar" %>
  </div>
  <%# SCRIPT FOR THE NAVBAR %>
  <script>
  document.addEventListener("DOMContentLoaded", function() {
    var navbar = document.querySelector('.navbar-homepage');
    var scrollThreshold = 680;
    var scrollButton = document.getElementById("scrollButton");

    window.addEventListener('scroll', function() {
      if (window.scrollY > scrollThreshold) {
        navbar.classList.add('navbar-scrolled');
        scrollButton.style.display = "block";
      } else {
        navbar.classList.remove('navbar-scrolled');
        scrollButton.style.display = "none";
      }
    });

    scrollButton.addEventListener("click", function() {
      window.location.href = "/lessons/new";
    });
  });
  </script>


  <%# HEADER SECTION %>
  <div class="header-section d-flex flex-column justify-content-end"
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= asset_path('home/header.jpg') %>');">
      <h1>YOUR PERSONNAL GUIDE</h1>
      <h1>TO MOVEMENT IN CONSCIOUSNESS</h1>
      <div class="button-homepage">
        <%= link_to "Get started", new_lesson_path, class: "orange-btn" %>
      </div>
  </div>

  <div style="height: 50px;"></div>


  <%# ----------------- CONTENT SECTION --------------------%>

  <%# SECTION 1 %>
  <div class="container">
    <%# -------- 📌 Relative ---------%>
    <div class="d-flex align-items-end" style="position: relative;">
      <%# DIV LEFT (📷) %>
      <div style="flex: 45%;">
        <%= image_tag('home/image1.jpg', alt: 'Image 1', class: 'home-image', style: 'border-radius: 20px;') %>
      </div>

      <%# DIV RIGHT (📃) %>
      <div style="display: flex; flex-direction: column; justify-content: flex-end">
        <%# -------- 📌 Absolute ---------%>
        <h2 style="position: absolute; width: 100%; left: 390px; top: 15px;" class="title-spicy-1">
          Breath Couture - Customize Your Exhale
        </h2>
        <div style="padding-left: 30px; text-align: justify;">
          <h3 style="padding-bottom: 30px;">Choose what is the best for you</h3>

            <p>Find breathing technique to lower stress and bring focus. They take just few
            minutes and can be done from everywhere.</p>
            <p>These accessible breathing techniques offer a quick respite in the midst of a
            hectic day. As you inhale and exhale with intention, the rhythm of your breath
            becomes an anchor, grounding you in the present moment.</p>
            <p> One effective method is the Nadi Shodhana breathing technique. With this practice,
            you alternate inhaling and exhaling through each nostril while using your fingers to
            regulate airflow. This rhythmic breathwork harmonizes the left and right hemispheres
            of the brain, promoting balance and reducing stress. Regular Nadi Shodhana practice
            can lead to improved focus and a calmer mind. </p>
        </div>
      </div>
    </div>
  </div>




    <div style="height: 150px;"></div>




  <%# SECTION 2 %>
  <div class="container">
    <%# -------- 📌 Relative ---------%>
    <div class="d-flex align-items-end" style="position: relative;">

      <%# DIV LEFT (📃) %>
      <div style="display: flex; flex-direction: column; justify-content: flex-end">
        <%# -------- 📌 Absolute ---------%>
        <h2 style="position: absolute; width: 100%; left: 264px; top: 15px;" class="title-spicy-2">
          Posture Play - Design Your Flow
        </h2>
        <div style="padding-right: 30px; text-align: justify;">
          <h3 style="padding-bottom: 30px;">Choose what is the best for you</h3>

            <p>Choose your own yoga class for body, mind, and spirit. Improve your balance, strengh
            and flexibiliy with classes for all levels. </p>
            <p> As you embark on this journey, consider the art of designing your yoga practice to align
            with your goals and aspirations. Embrace a range of dynamic asanas that challenge your body
            and invigorate your spirit, allowing you to push boundaries and discover new levels of strength.</p>
            <p>By curating your practice with a mix of invigorating and calming postures, you'll craft a balanced
            routine that that foster a deep mind-body connection, enhancing your mental clarity and focus. Just
            as life is a collection of experiences, your yoga mat becomes a canvas for self-expression and growth. </p>
        </div>
      </div>

      <%# DIV RIGHT (📷) %>
      <div style="flex: 45%;">
        <%= image_tag('home/image2.jpg', alt: 'Image 1', class: 'home-image', style: 'border-radius: 20px;') %>
      </div>
    </div>
  </div>



  <div style="height: 150px;"></div>




  <%# SECTION 3 %>
  <div class="container">
    <%# -------- 📌 Relative ---------%>
    <div class="d-flex align-items-end" style="position: relative;">
      <%# DIV LEFT (📷) %>
      <div style="flex: 45%;">
        <%= image_tag('home/image3.jpg', alt: 'Image 1', class: 'home-image', style: 'border-radius: 20px;') %>
      </div>

      <%# DIV RIGHT (📃) %>
      <div style="display: flex; flex-direction: column; justify-content: flex-end">
        <%# -------- 📌 Absolute ---------%>
        <h2 style="position: absolute; width: 100%; left: 390px; top: 15px;" class="title-spicy-3">
          Meditation Map - Shape Your Serenity
        </h2>
        <div style="padding-left: 30px; text-align: justify;">
          <h3 style="padding-bottom: 30px;">Choose what is the best for you</h3>

            <p>Try meditation for improved focus, concentration, and cultivating positive habits. With a few daily minutes, you can create a peaceful mental space. Mindfulness meditation, observing thoughts without judgment, nurtures self-acceptance. Guided sessions offer structured techniques to guide your focus.</p>
            <p>Meditation fosters presence, enriching engagement in daily activities. These moments of mindfulness extend self-kindness and self-connection. Integrate meditation to explore personal growth with a foundation of self-awareness.</p>
            <p>Furthermore, meditation nurtures a harmonious relationship with thoughts, reducing the pull of distractions. It's a practice that encourages clarity, focus, and self-love, inviting positive habits."</p>
        </div>
      </div>
    </div>
  </div>



  <div style="height: 150px;"></div>



  <%# SECTION 4 %>
  <div class="container">
    <%# -------- 📌 Relative ---------%>
    <div class="d-flex align-items-end" style="position: relative;">

      <%# DIV LEFT (📃) %>
      <div style="display: flex; flex-direction: column; justify-content: flex-end">
        <%# -------- 📌 Absolute ---------%>
        <h2 style="position: absolute; width: 100%; left: 264px; top: 15px;" class="title-spicy-4">
          Choose Your Duration, Level, Boost
        </h2>
        <div style="padding-right: 30px; text-align: justify;">
          <h3 style="padding-bottom: 30px;">Choose what is the best for you</h3>

            <p>Engage in a truly individualized practice that caters to your unique needs and aspirations. Whether you're a beginner seeking gentle guidance or an experienced practitioner craving challenges, our adaptable approach ensures a rewarding experience. </p>
            <p>By customizing each session, you'll find yourself embracing the mat with enthusiasm and anticipation. The added boost further amplifies your progress, addressing areas you wish to nurture – be it flexibility, strength, or mindfulness. Step onto your mat with the confidence that every breath, every posture, is tailored to sculpt your path towards a more enriched and fulfilling journey.</p>
        </div>
      </div>

      <%# DIV RIGHT (📷) %>
      <div style="flex: 45%;">
        <%= image_tag('home/image4.jpg', alt: 'Image 1', class: 'home-image', style: 'border-radius: 20px;') %>
      </div>
    </div>
  </div>


  <div style="height: 150px;"></div>



  <%#                    ---------------------------                      %>


  <div class="col-md-12 d-flex justify-content-center">
    <div class="text-center">
      <h2 class="spicy-rice-title" style="margin-top: 20px; margin-bottom: 30px;">Let's begin your journey now!</h2>
      <br>
      <%= link_to "Get started", new_lesson_path, class: "orange-btn" %>
    </div>
  </div>


  <%# A little margin between the content and the Footer (adjust accordinly) %>
  <div style="height: 250px;"></div>


  <%# Footer %>
  <%= render "shared/footer" %>
  </div>
</div>

app/views/pages/profile.html.erb
<div id="profilepages">
  <!-- PROFILE -->
    <div class="profile-infos-card d-flex flex-column justify-content-center " >
      <div class="d-flex justify-content-center">
          <%= cl_image_tag @user.avatar.key, class: "user-avatar", alt: "User Avatar" %>
      </div>
      <div class="d-flex justify-content-center">
        <p class= "hello-name-profile"> Hello <%= @user.username %> ! </p>
      </div>
        <div class="d-flex justify-content-center">
          <p>  <i class="fa-solid fa-user-plus fa-fade fa-xl" style="color: #C27E62;"></i>        <%= @user.xp%>  XP </p>
          <p class="px-5"> <i class="fa-solid fa-rocket fa-fade fa-xl" style="color: #C27E62;"></i>       <%= @user.level %></p>
          <p> <i class="fa-solid fa-trophy fa-fade fa-xl" style="color:#C27E62;"></i>        <%= @user.reward %></p>
        </div>
      <%# Calendar %>
    </div>

  <!-- FAVORITES -->
  <div class="profil-videos-container">
    <h3 class="title-profil-video">Favorites</h3>
    <div>
      <div class="scrolling-wrapper d-flex">
        <% @favorites.each do |favorite| %>
          <div class="s-card">
            <div class="s-card-media">
              <iframe width="350" height="250" src="<%= favorite.lesson.video_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
            <div class="card-bottom-main-div">
              <div class="card-bottom-left-div">
                <span class="title-card-profile" ><%= link_to favorite.lesson.name, lesson_path(favorite.lesson) %> </span>
                <br>
                <span class="custom-subtext-card">
                  <%= favorite.lesson.start_time.strftime('%d %b') %> -
                    <span class="custom-subtext-card"><%= favorite.lesson.duration %> min</span>
                  </span>
                </div>
                <div class="card-bottom-right-div" data-controller="popover" data-bs-toggle="popover" data-bs-trigger="hover" data-bs-placement="bottom" title="" data-bs-content="Do you want to delete this favorite?">
                  <%= button_to favorite_path(favorite), method: :delete, form_class: 'delete-alertbox', class: 'd-inline', class: 'no-border-sweet-alert' do %>
                    <i class="fa-solid fa-trash fa-lg" style="color: #000000;"></i>
                  <% end %>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  <br>

  <!-- HISTORY -->
  <div class="profil-videos-container">
    <h3 class="title-profil-video">History</h3>
    <div>
      <div class="scrolling-wrapper d-flex">
          <% @lessons.each do |lesson| %>
            <div class="s-card">
              <div class="s-card-media">
                <iframe width="350" height="250" src="<%= lesson.video_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
              </div>
              <div class="card-bottom-main-div">
                <div class="card-bottom-left-div">
                  <span class="title-card-profile" ><%= link_to lesson.name, lesson_path(lesson) %> </span>
                  <br>
                  <span class="custom-subtext-card">
                    <%= lesson.created_at.strftime('%d %b') %> -
                    <span class="custom-subtext-card"><%= lesson.duration %> min</span>
                  </span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="button-profile mt-5 mb-4 ">
    <%= link_to "Home", root_path, class: "green-btn" %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">

  <!-- PROFILE -->
  <div class="profile-infos-card">
    <%= cl_image_tag @user.avatar.key, class: "user-avatar", alt: "User Avatar" %>
    <p><strong>Email: </strong><%= @user.email %></p>
    <p><strong>Username: </strong><%= @user.username %></p>

    <%= link_to 'Update Profile', edit_user_registration_path, class: 'update-profile-btn' %>
  </div>

  <!-- LESSONS -->
  <div>
    <h3>LESSONS:</h3>
    <div class="lessons-infos-grid">
      <% @favorites.each do |favorite| %>
        <div class="lesson-card">
          <iframe width="350" height="250" src="<%= favorite.lesson.video_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          <h3><%= favorite.lesson.name %></h3>
          <i class="fa-solid fa-clock" style="color: #5c5c5c;"></i><%= favorite.lesson.duration %>
          <i class="fa-solid fa-layer-group" style="color: #5c5c5c;"></i><%= favorite.lesson.level %>
          <i class="fa-solid fa-bolt" style="color: #5c5c5c;"></i><%= favorite.lesson.boost %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Go back to HOME", root_path, class: "btn btn-primary mt-5" %>
</div>

app/views/shared/_card_breathing.html.erb
<div class="s-card d-flex flex-column justify-content-end " style="background-image: url(<%= image_path('lesson/card2.jpg') %>);">

  <div class="bottom-band d-flex justify-content-between align-items-center" >
    <div>
      <h3 class="title-card"> Breathing </h3>
      <p class="subtitle-card"> 30s - 15min </p>
    </div>
    <div class = "uncheked-box">  </div>
  </div>
</div>

app/views/shared/_card_meditation.html.erb
<div class="s-card d-flex flex-column justify-content-end " style="background-image: url(<%= image_path('lesson/card3.jpg') %>);">

  <div class="bottom-band d-flex justify-content-between align-items-center" >
    <div>
      <h3 class="title-card"> Meditation </h3>
      <p class="subtitle-card"> 5mn - 20mn  </p>
    </div>
    <div class = "uncheked-box">  </div>
  </div>
</div>

app/views/shared/_card_posture.html.erb
<div class="s-card d-flex flex-column justify-content-end " style="background-image: url(<%= image_path('lesson/card1.jpg') %>);">

  <div class="bottom-band d-flex justify-content-between align-items-center" >
    <div>
      <h3 class="title-card"> Posture </h3>
      <p class="subtitle-card"> Choose your level & boost </p>
    </div>
    <div class = "uncheked-box">  </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid" style="padding: 0 60px;">
    <%= link_to "SunnYogi", root_path, class: "text-link #{'white-link' if current_page?(root_path)}" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="nav-item" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="d-flex custom-20px-gap-navbar">
            <%= link_to lessons_path, class: "orange-btn-calendar" do %>
              <i class="fa-regular fa-calendar-days" style="color: #fefeebde"></i>
            <% end %>
            <%= link_to "Get started", new_lesson_path, class: "orange-btn", id: "scrollButton"  %>
            <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag @user.avatar.key, class: "user-avatar-navbar", alt: "User Avatar" %>
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"
              style="border-radius: 10px; padding: 5px;">
                <%#= link_to "New lesson", new_lesson_path, class: "dropdown-item" %>
                <%= link_to new_lesson_path, class: "dropdown-item" do %>
                  <i class="fa-brands fa-youtube fa-xl" style="color: #181616;"></i>
                <% end %>
                <%= link_to profile_path, class: "dropdown-item" do %>
                  <i class="fa-solid fa-user fa-lg" style="color: #181616;"></i>
                <% end %>
                <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
                  <i class="fa-solid fa-right-from-bracket fa-lg" style="color: #181616;"></i>
                <% end %>
              </div>
            </li>
          </div>
          <% else %>
            <div class="d-flex custom-20px-gap-navbar">
              <%= link_to lessons_path, class: "orange-btn-calendar" do %>
                <i class="fa-regular fa-calendar-days" style="color: white;"></i>
              <% end %>
              <%= link_to "Get started", new_lesson_path, class: "orange-btn", id: "scrollButton"  %>
              <%= link_to "Login", new_user_session_path, class: "orange-btn" %>
            </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>